function [ handles ] = drawPuma( joint_angles, puma )
% MECH 498 - Intro to Robotics - Spring 2014
% Lab 3 - Inverse Kinematics
%
%
%    DESCRIPTION - Plot a graphical representation of the PUMA 560
%    Industrial robot with attached coordinate frames, including the tool
%    attached to the end effector.
%
%    INPUTS - joint_angles is a 6-element vector of PUMA joint angles to
%                  specify the pose in which we wish to draw the PUMA.
%    
%             puma is a structure generated by pumaInit()
%
%    OUTPUTS - handles is a vector of graphics handles corresponding to the
%                  moving frames attached to the robot
%
%    ADDITIONAL CODE NEEDED:
%   
%    The function pumaFK() must be completed in order to run this function.
%
%    Make sure you understand the section of code marked "Draw Robot", and
%    duplicate for the remaining links and the tool what has already been
%    done for links 0 and 1
%

% Create a cell array of PUMA forward kinematics transforms
[~,puma_T] = pumaFK(joint_angles,puma);

% Shorten variable names
L_1 = puma.parameters.L_1;
L_2 = puma.parameters.L_2;
L_3 = puma.parameters.L_3;
L_4 = puma.parameters.L_4;
L_5 = puma.parameters.L_5;
L_6 = puma.parameters.L_6;

l_23=L_2-L_4;


a_1 = puma.parameters.a_1;
a_2 = puma.parameters.a_2;
a_3 = puma.parameters.a_3;
a_4 = puma.parameters.a_4;



% Plot scaling properties
origin_size = 20;
marker_size = 10;
vector_size = 0.05*max(abs(diff(reshape(puma.workspace,2,3))));

% Create figure window
figure('Color','w');

% Create axes object
ax = axes('XLim',puma.workspace(1:2),'YLim',puma.workspace(3:4),...
   'ZLim',puma.workspace(5:6));
view(3);
grid on;
axis equal;
xlabel('X (mm)','FontSize',16);
ylabel('Y (mm)','FontSize',16);
zlabel('Z (mm)','FontSize',16);

%%%%%%%%%%%%%%%%%%%%%%%%%%%% Draw Robot %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Create link 0 and frame 0
h = drawRobotFrame([0,0,0]);
hg = hggroup('Parent',ax);
set(h,'Parent',hg);
L_0 = line(100*cos(0:1e-2:2*pi),100*sin(0:1e-2:2*pi),...
    -L_1*ones(length(0:1e-2:2*pi)),...
    'Color','r','LineWidth',1.5);
set(L_0,'Parent',hg);
T_0 = hgtransform('Parent',ax,'Matrix',makehgtform('translate',[0,0,L_1]));
set(hg,'Parent',T_0);

% Create link 1 and frame 1
h = drawRobotFrame(puma.colors{1});
hg = hggroup('Parent',ax);
set(h,'Parent',hg);
L_1 = line([0,0,0],[0,0,L_2],[-L_1,0,0],...
    'Color',puma.colors{1},'LineWidth',1.5);
set(L_1,'Parent',hg);
T_1 = hgtransform('Parent',T_0,'Matrix',puma_T{1});
set(hg,'Parent',T_1);


% Create link 2 and frame 2
h = drawRobotFrame(puma.colors{2});
hg = hggroup('Parent',ax);
set(h,'Parent',hg);
L_2 = line([0,L_3,L_3],[0,0,0],[L_2,L_2,L_2],'Color',puma.colors{2},'LineWidth',1.5);
set(L_2,'Parent',hg);
T_2 = hgtransform('Parent',T_1,'Matrix',puma_T{2});
set(hg,'Parent',T_2);
L_3


% Create link 3 and frame 3
h = drawRobotFrame(puma.colors{3});
hg = hggroup('Parent',ax);
set(h,'Parent',hg);
L_3 = line([0,0,0],[0,0,L_6],[l_23,0,0],'Color',puma.colors{3},'LineWidth',1.5);
set(L_3,'Parent',hg);
T_3 = hgtransform('Parent',T_2,'Matrix',puma_T{3});
set(hg,'Parent',T_3);


% Create link 4 and frame 4
h = drawRobotFrame(puma.colors{4});
hg = hggroup('Parent',ax);
set(h,'Parent',hg);
L_4 = line([0,0,0],[0,0,0],[0,0,0],'Color',puma.colors{4},'LineWidth',1.5);
set(L_4,'Parent',hg);
T_4 = hgtransform('Parent',T_3,'Matrix',puma_T{4});
set(hg,'Parent',T_4);



% Create link 5 and frame 5
h = drawRobotFrame(puma.colors{5});
hg = hggroup('Parent',ax);
set(h,'Parent',hg);
L_5 = line([0,0,0],[0,0,0],[0,0,0],'Color',puma.colors{5},'LineWidth',1.5);
set(L_5,'Parent',hg);
T_5 = hgtransform('Parent',T_4,'Matrix',puma_T{5});
set(hg,'Parent',T_5);


% Create link 6 and frame 6
h = drawRobotFrame(puma.colors{6});
hg = hggroup('Parent',ax);
set(h,'Parent',hg);
L_6 = line([0,0,0],[0,0,0],[0,0,0],'Color',puma.colors{6},'LineWidth',1.5);
set(L_6,'Parent',hg);
T_6 = hgtransform('Parent',T_5,'Matrix',puma_T{6});
set(hg,'Parent',T_6);


% Create link 7 and frame 7
h = drawRobotFrame(puma.colors{7});
hg = hggroup('Parent',ax);
set(h,'Parent',hg);
L_7 = line([0,0,-50],[0,0,-50],[0,-25,-50],'Color',puma.colors{7},'LineWidth',3);
set(L_7,'Parent',hg);
T_7 = hgtransform('Parent',T_6,'Matrix',puma_T{6});
set(hg,'Parent',T_7);







% Render graphics
set(gcf,'Renderer','openGL');
drawnow;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


% Return hgtransform handles

handles = [T_1,T_2,T_3,T_4,T_5,T_6,T_7];

    function h = drawRobotFrame( color )
         
        % Plot reference frame
        X_b = [vector_size,0,0,1]';
        Y_b = [0,vector_size,0,1]';
        Z_b = [0,0,vector_size,1]';
        h(1) = line(0,0,0,'Marker','.','MarkerSize',origin_size,'Color',color);
        h(2) = line([0,X_b(1)],[0,X_b(2)],[0,X_b(3)],'LineWidth',1.5,'Color',color);
        h(3) = line([0,Y_b(1)],[0,Y_b(2)],[0,Y_b(3)],'LineWidth',1.5,'Color',color);
        h(4) = line([0,Z_b(1)],[0,Z_b(2)],[0,Z_b(3)],'LineWidth',1.5,'Color',color);
        h(5) = line(X_b(1),X_b(2),X_b(3),'LineWidth',1.5,'Marker','x','MarkerSize',marker_size,'Color',color);
        h(6) = line(Y_b(1),Y_b(2),Y_b(3),'LineWidth',1.5,'Marker','o','MarkerSize',marker_size,'Color',color);
        h(7) = line(Z_b(1),Z_b(2),Z_b(3),'LineWidth',1.5,'Marker','d','MarkerSize',marker_size,'Color',color);
    end


end

